### ISSUE TITLE
Unknown runtume Error (seems to be root related) 

### ISSUE THREAD

**Issue by thesullivantage** [gwpy/pyomicron#133]
As suggested, using this virgosoft environment on ldas-grid:
/home/detchar/opt/virgosoft/environment.sh

Which produces this error when running on an hour of unbroken observing time: 
Omicron::ReadOptions: No output style (OUTPUT/STYLE)  --> set default: GWOLLUM
Fatal in <TROOT::InitInterpreter>: cannot load library /usr/lib64/root/libRIO.so: undefined symbol: _ZN10TClassEdit14ResolveTypedefEPKcb

I sidestepped this by using igwn-py38 (with good root installations) and making sure omicron was sufficiently installed per the workflow instructions, but it seemed like an environment issue.

**Comment by duncanmmacleod** [comment]
This is an issue with Omicron (the C++ application, see https://git.ligo.org/virgo/virgoapp/Omicron) and not pyomicron.
