### ISSUE TITLE
Parameter file generation tool

### ISSUE THREAD

**Issue by FlorentRobinet** [gwpy/pyomicron#25]
omicron-process currently generates a full condor workflow. It may be useful to have a separate tool, "omicron-parameters" designed to only generate parameter files, given a list of channels and a set of parameters.
NO htcondor dependencies is required.

**Comment by duncanmmacleod** [comment]
@FlorentRobinet, I think I'm finally in a position to actually do something about this. But, I would like to get some more details from you. Do you imagine such a tool will generate the frame cache file, and segments files, then the parameters files? Or do you want placeholders for those to be customised by hand?

**Comment by FlorentRobinet** [comment]
No cache file generation is required. For Virgo, cache files are not generated on the fly. They already exist. Moreover, for the online omicron application, data are not accessed through frame files. Same comment for segment files.

What is required is to have a tool to generate a parameter file for omicron. So I imagine that the cache file can be provided using a user option. In fact, it should be possible to generate a parameter file without the DATA/FFL option which is not required for online omicron.

**Comment by eagoetz** [comment]
@FlorentRobinet @duncanmmacleod Since this issue is now 6 years old, if we don't hear otherwise, we'll proceed to close as not needing to be addressed. Let us know.
