### ISSUE TITLE
omicron-print events for arbitrary trigger files

### ISSUE THREAD

**Issue by FlorentRobinet** [gwpy/pyomicron#26]
For now, the omicron-print tool only accepts trigger files organized in a pre-defined directory structure. 
Request: add an option to provide any user trigger files.

**Comment by eagoetz** [comment]
@FlorentRobinet @duncanmmacleod Since this issue is now 6 years old, perhaps we can close it without addressing it. If we don't hear otherwise, we'll proceed to close as not needing to be addressed. Thanks.

**Comment by FlorentRobinet** [comment]
Yes, close.
