### ISSUE TITLE
omicron-root-merge is slow

### ISSUE THREAD

**Issue by FlorentRobinet** [gwpy/pyomicron#37]
The merging of root files with omicron-root-merge is slow. It is almost a factor 4 slower than the GWOLLUM application triggermerge.exe. See below:

farmn4[/data/omicron]> time omicron-root-merge V1/LSC_B7_6MHz_ERR_OMICRON/11594/V1-LSC_B7_6MHz_ERR_OMICRON-1159408655-4000.root V1/LSC_B7_6MHz_ERR_OMICRON/11594/V1-LSC_B7_6MHz_ERR_OMICRON-1159484703-4000.root test.root
**1.265u 0.889s 0:06.40 33.4%   0+0k 32000+2368io 39pf+0w**

farmn4[/data/omicron]> time triggermerge.exe . "V1/LSC_B7_6MHz_ERR_OMICRON/11594/V1-LSC_B7_6MHz_ERR_OMICRON-1159408655-4000.root V1/LSC_B7_6MHz_ERR_OMICRON/11594/V1-LSC_B7_6MHz_ERR_OMICRON-1159484703-4000.root"
**0.715u 0.272s 0:02.19 44.7%   0+0k 864+2344io 9pf+0w**

**Comment by duncanmmacleod** [comment]
thanks @FlorentRobinet, I can have a go at profiling the `omicron-root-merge` script, and see where the bottlenecks are.

**Comment by areeda** [comment]
Too old. and triggermerge is not in the conda gwollum package
